const fs = require('fs');
const path = require('path');
const test = require('tap').test;

const makeTestStorage = require('../fixtures/make-test-storage');
const VirtualMachine = require('../../src/virtual-machine');

// The 3D Pop-Up starter projects live in scratch-gui (they are generated by
// src/components/popup-examples-modal/starters/make-popup-examples.js). These headless
// checks load the three complex examples and verify the renderer-independent behaviour:
// they load cleanly, run on the green flag, and build their clones with the right
// inherited 3D properties. The full visual behaviour is covered by the editor Playwright
// spec (scratch-gui/test/playwright/popup-examples.spec.js).
const STARTERS = path.resolve(
    __dirname, '../../../scratch-gui/src/components/popup-examples-modal/starters'
);
const sb3Path = name => path.join(STARTERS, name);
const haveStarters = fs.existsSync(sb3Path('popup-example-7.sb3'));

const popupState = target => target.getCustomState('Scratch.popup');
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

const loadAndRun = async (file, steps) => {
    const vm = new VirtualMachine();
    vm.attachStorage(makeTestStorage());
    const errors = [];
    vm.on('error', e => errors.push(e));
    await vm.loadProject(fs.readFileSync(sb3Path(file)));
    vm.runtime.currentStepTime = 1000 / 30;
    vm.greenFlag();
    for (let i = 0; i < steps; i++) vm.runtime._step();
    return {vm, errors};
};

test('3D Pop-Up example 7 (platformer): platforms clone with inherited depths', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-7.sb3', 30).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const platforms = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Platform' && !target.isOriginal
        );
        t.equal(platforms.length, 3, 'three platform clones were created');
        const depths = platforms.map(p => popupState(p).depth).sort((a, b) => a - b);
        t.same(depths, [-60, 0, 60], 'clones inherited the three distinct depths');

        const hero = vm.runtime.targets.find(target => target.sprite.name === 'Hero' && target.isOriginal);
        t.ok(hero, 'the hero sprite exists');
        t.ok(Number.isFinite(popupState(hero).thickness), 'hero has 3D state');
        t.end();
    });
});

test('3D Pop-Up example 9 (crystal): crossed clones inherit distinct spins', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-9.sb3', 30).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const gems = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Crystal' && !target.isOriginal
        );
        t.equal(gems.length, 3, 'three crystal clones were created');
        const spins = gems.map(g => popupState(g).spin).sort((a, b) => a - b);
        t.same(spins, [0, 60, 120], 'clones inherited the three crossing angles');

        const halo = vm.runtime.targets.find(target => target.sprite.name === 'Halo' && target.isOriginal);
        t.equal(popupState(halo).tilt, 78, 'the halo ring is laid flat with a 78-degree tilt');
        t.end();
    });
});

test('3D Pop-Up example 8 (birthday): clicking a balloon pops it', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-8.sb3', 10).then(async ({vm, errors}) => {
        const red = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'RedBalloon');
        t.ok(red, 'the red balloon exists');
        t.equal(red.visible, true, 'balloon starts visible');

        // Fire the balloon's "when this sprite clicked" script (in the editor this is
        // triggered by clicking the 3D mesh). It says "Pop!" briefly, then grows + fades
        // and hides. Step with real time so the say timer elapses.
        const started = vm.runtime.startHats('event_whenthisspriteclicked', null, red);
        t.equal(started.length, 1, 'the click starts one script');
        for (let i = 0; i < 30; i++) {
            vm.runtime._step();
            await sleep(25);
        }
        t.equal(errors.length, 0, 'no runtime errors');
        t.equal(red.visible, false, 'the balloon has popped (hidden) after the click animation');
        t.end();
    });
});
