const fs = require('fs');
const path = require('path');
const test = require('tap').test;

const makeTestStorage = require('../fixtures/make-test-storage');
const VirtualMachine = require('../../src/virtual-machine');

// The 3D Pop-Up starter projects live in scratch-gui (they are generated by
// src/components/popup-examples-modal/starters/make-popup-examples.js). These headless
// checks load the three complex examples and verify the renderer-independent behaviour:
// they load cleanly, run on the green flag, and build their clones with the right
// inherited 3D properties. The full visual behaviour is covered by the editor Playwright
// spec (scratch-gui/test/playwright/popup-examples.spec.js).
const STARTERS = path.resolve(
    __dirname, '../../../scratch-gui/src/components/popup-examples-modal/starters'
);
const sb3Path = name => path.join(STARTERS, name);
const haveStarters = fs.existsSync(sb3Path('popup-example-7.sb3'));

const popupState = target => target.getCustomState('Scratch.popup');
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

const loadAndRun = async (file, steps) => {
    const vm = new VirtualMachine();
    vm.attachStorage(makeTestStorage());
    const errors = [];
    vm.on('error', e => errors.push(e));
    await vm.loadProject(fs.readFileSync(sb3Path(file)));
    vm.runtime.currentStepTime = 1000 / 30;
    vm.greenFlag();
    for (let i = 0; i < steps; i++) vm.runtime._step();
    return {vm, errors};
};

test('3D Pop-Up example 7 (platformer): platforms clone with inherited depths', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-7.sb3', 30).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const platforms = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Platform' && !target.isOriginal
        );
        t.equal(platforms.length, 8, 'all eight platform clones were created');
        const depths = platforms.map(p => popupState(p).depth).sort((a, b) => a - b);
        // Six climbing platforms at the same depth plus two decorative ledges (near / far).
        t.same(depths, [-60, 26, 26, 26, 26, 26, 26, 140], 'clones inherited their depths');

        const hero = vm.runtime.targets.find(target => target.sprite.name === 'Hero' && target.isOriginal);
        t.ok(hero, 'the hero sprite exists');
        t.ok(Number.isFinite(popupState(hero).thickness), 'hero has 3D state');

        const goal = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'Goal');
        t.ok(goal, 'the goal flag sprite exists');

        const stage = vm.runtime.getTargetForStage();
        const winVar = Object.values(stage.variables).find(v => v.name === 'Win');
        t.ok(winVar, 'the global Win flag exists');
        t.equal(Number(winVar && winVar.value), 0, 'Win is 0 before the goal is reached');
        t.end();
    });
});

test('3D Pop-Up example 13 (platform run): a staggered, ascending trail along depth', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-13.sb3', 30).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        // The extension is loaded by this project, so sprite fencing defaults to off.
        t.equal(vm.runtime.fencingEnabled, false, 'fencing is off while the extension is loaded');

        const tiles = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Platform' && !target.isOriginal
        );
        t.equal(tiles.length, 7, 'all seven tile clones were created');

        // The trail runs along the DEPTH axis: from 0 out to -2280 (toward the camera),
        // far past the old stage bounds.
        const depths = tiles.map(tile => popupState(tile).depth).sort((a, b) => a - b);
        t.equal(depths[0], -2280, 'the trail reaches almost 5 stage-widths out along depth');
        t.equal(depths[depths.length - 1], 0, 'the trail starts at the spawn tile');

        // Gradually ascending and staggered left/right; every tile lies flat (tilt 90).
        const byDepth = tiles.slice().sort((a, b) => popupState(b).depth - popupState(a).depth);
        for (let i = 1; i < byDepth.length; i++) {
            t.ok(byDepth[i].y > byDepth[i - 1].y, `tile ${i} sits higher than tile ${i - 1}`);
        }
        t.equal(byDepth[0].x, 0, 'the spawn tile sits on the centre line');
        t.ok(byDepth.slice(1).every((tile, i) => tile.x === (i % 2 === 0 ? 55 : -55)),
            'the tiles stagger 55 to alternating sides');
        t.ok(tiles.every(tile => popupState(tile).tilt === 90), 'every tile lies flat (tilt 90)');

        const goal = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'Goal');
        t.ok(goal, 'the goal flag sprite exists');
        t.equal(popupState(goal).depth, -2280, 'the goal stands at the far end of the trail');

        const stage = vm.runtime.getTargetForStage();
        const winVar = Object.values(stage.variables).find(v => v.name === 'Win');
        t.ok(winVar, 'the global Win flag exists');
        t.equal(Number(winVar && winVar.value), 0, 'Win is 0 before the goal is reached');
        t.end();
    });
});

test('3D Pop-Up example 14 (race day): a giant track map with gates, trees and houses', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-14.sb3', 30).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');
        t.equal(vm.runtime.fencingEnabled, false, 'fencing is off while the extension is loaded');

        // The whole track is one giant flat card: front face up (tilt -90), centred
        // 440 into the page so the start/finish line sits at depth 0.
        const track = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'Track');
        t.ok(track, 'the track map sprite exists');
        t.equal(popupState(track).tilt, -90, 'the map lies flat, front face up');
        t.equal(popupState(track).depth, 440, 'the map is centred 440 into the page');

        // Four checkered gates stand across the road, spun to match their straights.
        const gates = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Gate' && !target.isOriginal
        );
        t.equal(gates.length, 4, 'all four gate clones were created');
        const gateSpots = gates.map(g => [g.x, popupState(g).depth, popupState(g).spin])
            .sort((a, b) => a[0] - b[0]);
        t.same(gateSpots, [[-680, 440, 0], [-400, 0, 90], [0, 880, 90], [680, 440, 0]],
            'the gates stand across each straight of the ring road');

        // Trees are crossed pairs (spin 0 + 90 at each spot); houses are single clones.
        const trees = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Tree' && !target.isOriginal
        );
        t.equal(trees.length, 16, 'eight tree spots, two crossed clones each');
        t.equal(trees.filter(tree => popupState(tree).spin === 0).length, 8, 'half the tree cards face front');
        t.equal(trees.filter(tree => popupState(tree).spin === 90).length, 8, 'half the tree cards are crossed');
        const houses = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'House' && !target.isOriginal
        );
        t.equal(houses.length, 4, 'all four house clones were created');
        t.ok(houses.every(h => popupState(h).thickness === 60), 'houses are thick, boxy extrusions');

        // The car starts on the finish line facing down the bottom straight.
        const car = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'Car');
        t.ok(car, 'the car sprite exists');
        t.equal(popupState(car).depth, 0, 'the car starts on the finish line');
        t.equal(popupState(car).spin, -90, 'the car faces down the bottom straight');

        const stage = vm.runtime.getTargetForStage();
        const gatesVar = Object.values(stage.variables).find(v => v.name === 'Gates');
        t.ok(gatesVar, 'the global Gates counter exists');
        t.equal(Number(gatesVar && gatesVar.value), 0, 'no gates are passed at the start');
        t.end();
    });
});

test('3D Pop-Up example 9 (crystal): crossed clones inherit distinct spins', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-9.sb3', 30).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const gems = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Crystal' && !target.isOriginal
        );
        t.equal(gems.length, 3, 'three crystal clones were created');
        const spins = gems.map(g => popupState(g).spin).sort((a, b) => a - b);
        t.same(spins, [0, 60, 120], 'clones inherited the three crossing angles');

        const halo = vm.runtime.targets.find(target => target.sprite.name === 'Halo' && target.isOriginal);
        t.equal(popupState(halo).tilt, 78, 'the halo ring is laid flat with a 78-degree tilt');
        t.end();
    });
});

test('3D Pop-Up example 2 (fish tank): fish stay upright and turn back at the walls', {skip: !haveStarters}, t => {
    // Run long enough that the fish reach the side walls and do their spin-around turns.
    loadAndRun('popup-example-2.sb3', 400).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const fishNames = ['Clownfish', 'BlueTang', 'BannerFish', 'YellowTang'];
        const fish = vm.runtime.targets.filter(target => target.sprite && fishNames.includes(target.sprite.name));
        t.equal(fish.length, 4, 'all four library fish are present');
        // "stay right-side up": tilt is never touched, so every fish stays upright.
        t.ok(fish.every(f => popupState(f).tilt === 0), 'every fish stays upright (tilt 0)');
        // The quick spin-around (not a fly-off) keeps every fish inside the tank.
        t.ok(fish.every(f => Math.abs(f.x) < 235), 'every fish turned back and stayed within the walls');

        const decor = ['Sand', 'Coral1', 'Coral2', 'Kelp1', 'Kelp2'];
        t.ok(decor.every(name => vm.runtime.targets.some(tg => tg.sprite && tg.sprite.name === name)),
            'the sand, coral and kelp sprites are all present');
        t.end();
    });
});

test('3D Pop-Up example 10 (solar system): planets orbit away from their start', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-10.sb3', 20).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        // Each planet starts on the +x axis (depth 0) and is walked around the centre by
        // the `orbit` block, so after a few frames it has left its starting spot.
        const earth = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'Earth');
        t.ok(earth, 'the Earth sprite exists');
        const moved = Math.hypot(earth.x - 95, popupState(earth).depth);
        t.ok(moved > 5, 'Earth has orbited away from its starting position');
        t.end();
    });
});

test('3D Pop-Up example 11 (gem hunt): gems clone and the score is global', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-11.sb3', 5).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const gems = vm.runtime.targets.filter(
            target => target.sprite && target.sprite.name === 'Gem' && !target.isOriginal
        );
        t.equal(gems.length, 5, 'five gem clones were created');
        const stage = vm.runtime.getTargetForStage();
        const hasScore = Object.values(stage.variables).some(v => v.name === 'Gems');
        t.ok(hasScore, 'the Gems score is a global (stage) variable');
        t.end();
    });
});

test('3D Pop-Up example 12 (carousel): six horses are spaced evenly around the centre', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-12.sb3', 5).then(({vm, errors}) => {
        t.equal(errors.length, 0, 'no runtime errors');

        const horses = vm.runtime.targets.filter(
            target => target.sprite && /^Horse/.test(target.sprite.name) && !target.isOriginal
        );
        t.equal(horses.length, 6, 'six horse clones were created (three of each colour)');
        // The horses start the same radius from the centre, just at different angles.
        const radii = horses.map(h => Math.hypot(h.x, popupState(h).depth));
        for (const r of radii) t.ok(Math.abs(r - 120) < 1, 'each horse sits ~120 units from the centre');
        t.end();
    });
});

test('3D Pop-Up example 8 (birthday): clicking a balloon pops it', {skip: !haveStarters}, t => {
    loadAndRun('popup-example-8.sb3', 10).then(async ({vm, errors}) => {
        const red = vm.runtime.targets.find(target => target.sprite && target.sprite.name === 'RedBalloon');
        t.ok(red, 'the red balloon exists');
        t.equal(red.visible, true, 'balloon starts visible');

        // Fire the balloon's "when this sprite clicked" script (in the editor this is
        // triggered by clicking the 3D mesh). It says "Pop!" briefly, then grows + fades
        // and hides. Step with real time so the say timer elapses.
        const started = vm.runtime.startHats('event_whenthisspriteclicked', null, red);
        t.equal(started.length, 1, 'the click starts one script');
        for (let i = 0; i < 30; i++) {
            vm.runtime._step();
            await sleep(25);
        }
        t.equal(errors.length, 0, 'no runtime errors');
        t.equal(red.visible, false, 'the balloon has popped (hidden) after the click animation');
        t.end();
    });
});
