module.exports = {
    animals: [
        'a cat', 'a dog', 'a bird', 'a fish', 'a horse', 'a cow', 'a sheep', 'a goat', 'a pig', 'a chicken',
        'a duck', 'a goose', 'a rabbit', 'a hamster', 'a mouse', 'a rat', 'a squirrel', 'a hedgehog', 'a bat', 'a fox',
        'a wolf', 'a bear', 'a panda', 'a polar bear', 'a koala', 'a kangaroo', 'a deer', 'a moose', 'a zebra', 'a giraffe',
        'an elephant', 'a hippo', 'a rhinoceros', 'a lion', 'a tiger', 'a leopard', 'a cheetah', 'a jaguar', 'a monkey', 'a gorilla',
        'a chimpanzee', 'an orangutan', 'a sloth', 'an armadillo', 'a raccoon', 'a skunk', 'a beaver', 'an otter', 'a seal', 'a walrus',
        'a dolphin', 'a whale', 'a shark', 'an octopus', 'a squid', 'a jellyfish', 'a crab', 'a lobster', 'a snail', 'a snake',
        'a lizard', 'a turtle', 'a frog', 'a toad', 'a salamander', 'a crocodile', 'an alligator', 'an owl', 'an eagle', 'a hawk',
        'a parrot', 'a penguin', 'a flamingo', 'a peacock', 'a swan', 'a butterfly', 'a bee', 'a ladybug', 'an ant', 'a spider'
    ],
    weather: [
        'a sunny day', 'a partly cloudy day', 'a cloudy day', 'an overcast sky', 'a clear blue sky', 'a bright sunny sky',
        'a rainy day', 'a light drizzle', 'a heavy rainstorm', 'a thunderstorm with lightning', 'a flash of lightning',
        'a snowy day', 'light snowfall', 'a heavy blizzard', 'a snow-covered landscape', 'snow falling outside',
        'a foggy morning', 'thick fog rolling in', 'a misty day', 'morning mist',
        'a windy day', 'leaves blowing in the wind', 'a hurricane', 'a tornado', 'a dust storm',
        'a hailstorm', 'hail on the ground', 'a sleet storm', 'an icy day', 'frost on the window',
        'a colorful sunrise', 'a beautiful sunset', 'twilight in the sky', 'a starry night sky', 'a full moon at night',
        'a crescent moon', 'a rainbow after rain', 'a double rainbow', 'a dramatic stormy sky', 'puffy white clouds',
        'dark storm clouds', 'wispy cirrus clouds', 'a smoky hazy sky', 'a hot summer day', 'a cold winter day',
        'a humid day', 'a dry desert day', 'a chilly autumn day', 'a fresh spring morning', 'a tropical storm',
        'a calm peaceful sky', 'a hazy sunset', 'glowing northern lights', 'a moonlit night', 'snowflakes falling',
        'raindrops on a window', 'a flooded street', 'mud after rain', 'puddles everywhere', 'morning dew on grass'
    ],
    colors: [
        'mostly red', 'mostly bright red', 'mostly dark red', 'mostly crimson', 'mostly maroon',
        'mostly orange', 'mostly bright orange', 'mostly dark orange', 'mostly peach',
        'mostly yellow', 'mostly bright yellow', 'mostly pale yellow', 'mostly mustard yellow', 'mostly gold',
        'mostly green', 'mostly bright green', 'mostly dark green', 'mostly lime green', 'mostly forest green', 'mostly mint green',
        'mostly teal', 'mostly turquoise', 'mostly cyan',
        'mostly blue', 'mostly bright blue', 'mostly dark blue', 'mostly navy blue', 'mostly sky blue', 'mostly baby blue',
        'mostly purple', 'mostly bright purple', 'mostly dark purple', 'mostly violet', 'mostly lavender', 'mostly indigo', 'mostly magenta',
        'mostly pink', 'mostly bright pink', 'mostly hot pink', 'mostly light pink', 'mostly rose',
        'mostly brown', 'mostly light brown', 'mostly dark brown', 'mostly chocolate', 'mostly tan', 'mostly beige',
        'mostly black', 'mostly dark gray', 'mostly gray', 'mostly silver', 'mostly light gray', 'mostly white',
        'mostly cream', 'a colorful rainbow of colors', 'a black and white image', 'a sepia tone image', 'a pastel color palette',
        'mostly neon colors', 'mostly muted earth tones'
    ],
    vehicles: [
        'a car', 'a small car', 'a sports car', 'a race car', 'a convertible', 'a sedan', 'an SUV',
        'a truck', 'a pickup truck', 'a dump truck', 'a fire truck', 'a tow truck', 'a semi truck',
        'a bus', 'a school bus', 'a double decker bus', 'a tour bus',
        'a van', 'a minivan', 'a delivery van',
        'a bicycle', 'a mountain bike', 'a road bike', 'a unicycle', 'a tricycle',
        'a motorcycle', 'a scooter', 'a moped',
        'an airplane', 'a jet plane', 'a propeller plane', 'a fighter jet', 'a passenger airliner',
        'a helicopter', 'a drone', 'a hot air balloon', 'a blimp', 'a glider',
        'a rocket', 'a space shuttle', 'a spaceship', 'a satellite',
        'a boat', 'a sailboat', 'a speedboat', 'a fishing boat', 'a rowboat', 'a canoe', 'a kayak',
        'a ship', 'a cruise ship', 'a cargo ship', 'a tugboat', 'a submarine', 'a yacht',
        'a train', 'a steam train', 'a freight train', 'a high speed train', 'a subway train', 'a monorail',
        'a tram', 'a streetcar',
        'a tractor', 'a bulldozer', 'an excavator', 'a forklift', 'a snowmobile', 'a jet ski',
        'a skateboard', 'roller skates', 'a wheelchair', 'a horse drawn carriage', 'a wagon', 'a golf cart'
    ],
    emotions: [
        'a happy face', 'a smiling face', 'a laughing face', 'a grinning face', 'a joyful expression',
        'a sad face', 'a crying face', 'a tearful face', 'a sobbing face', 'a frowning face',
        'an angry face', 'a furious face', 'a glaring face', 'a scowling face', 'an annoyed face',
        'a surprised face', 'a shocked face', 'an amazed face', 'a stunned face', 'a face with wide eyes',
        'a scared face', 'a frightened face', 'a terrified face', 'a worried face', 'an anxious face',
        'a confused face', 'a puzzled face', 'a thinking face', 'a curious face',
        'a neutral face', 'a calm face', 'a relaxed face', 'a peaceful face', 'a serene face',
        'a sleepy face', 'a tired face', 'a yawning face', 'an exhausted face',
        'a disgusted face', 'a grossed out face', 'a sick face', 'a queasy face',
        'an excited face', 'an enthusiastic face', 'a cheerful face', 'an ecstatic face',
        'a bored face', 'an unimpressed face', 'a disappointed face',
        'a proud face', 'a confident face', 'a smug face',
        'a shy face', 'an embarrassed face', 'a blushing face', 'a bashful face',
        'a loving face', 'an affectionate face', 'a face blowing a kiss', 'a face in love',
        'a winking face', 'a playful face', 'a silly face', 'a mischievous face'
    ],
    objects: [
        'a ball', 'a basketball', 'a soccer ball', 'a baseball', 'a tennis ball', 'a football',
        'a book', 'a notebook', 'a magazine', 'a newspaper', 'a stack of books',
        'a chair', 'a wooden chair', 'an office chair', 'a rocking chair', 'a bench', 'a stool', 'a sofa',
        'a table', 'a desk', 'a dining table', 'a coffee table', 'a nightstand',
        'a cup', 'a coffee mug', 'a tea cup', 'a glass', 'a wine glass', 'a water bottle', 'a thermos',
        'a phone', 'a smartphone', 'an old telephone', 'a tablet',
        'a computer', 'a laptop', 'a desktop computer', 'a computer monitor', 'a keyboard', 'a mouse',
        'a pencil', 'a pen', 'a marker', 'a crayon', 'a paintbrush',
        'a backpack', 'a suitcase', 'a handbag', 'a wallet', 'a purse',
        'a clock', 'a wall clock', 'a wristwatch', 'an alarm clock',
        'a lamp', 'a flashlight', 'a candle', 'a lantern',
        'scissors', 'a stapler', 'a tape dispenser', 'a ruler', 'an eraser',
        'a hammer', 'a screwdriver', 'a wrench', 'a saw', 'a drill',
        'a key', 'a door', 'a window', 'a mirror', 'a picture frame', 'a poster',
        'a plate', 'a bowl', 'a spoon', 'a fork', 'a knife', 'a pot', 'a pan',
        'a remote control', 'a game controller', 'a camera', 'a pair of headphones', 'a pair of earbuds',
        'a pair of glasses', 'a pair of sunglasses', 'a hat', 'a baseball cap', 'a scarf', 'an umbrella',
        'a toy', 'a stuffed animal', 'a doll', 'a teddy bear', 'a building block toy'
    ],
    food: [
        'a pizza', 'a slice of pizza', 'a whole pizza pie',
        'a hamburger', 'a cheeseburger', 'a hot dog', 'a sandwich', 'a sub sandwich', 'a wrap', 'a burrito', 'a taco',
        'french fries', 'onion rings', 'potato chips', 'popcorn', 'pretzels',
        'a pasta dish', 'spaghetti', 'macaroni and cheese', 'lasagna', 'ravioli',
        'a salad', 'a green salad', 'a fruit salad', 'a caesar salad',
        'a soup', 'a bowl of soup', 'chicken noodle soup', 'tomato soup',
        'a steak', 'roast chicken', 'fried chicken', 'fish and chips', 'sushi', 'a sushi roll',
        'an apple', 'a banana', 'an orange', 'a strawberry', 'a bunch of grapes', 'a watermelon slice',
        'a pineapple', 'a mango', 'a peach', 'a pear', 'a cherry', 'a lemon', 'a lime', 'a blueberry', 'a raspberry',
        'a tomato', 'a carrot', 'broccoli', 'lettuce', 'a cucumber', 'a bell pepper', 'an onion', 'a potato', 'corn on the cob',
        'a slice of bread', 'a loaf of bread', 'a bagel', 'a croissant', 'a donut', 'a muffin', 'a pancake', 'a waffle',
        'a slice of cake', 'a birthday cake', 'a cupcake', 'a cookie', 'a brownie', 'a pie', 'an apple pie',
        'ice cream', 'an ice cream cone', 'a popsicle', 'a milkshake',
        'a candy bar', 'chocolate', 'a piece of chocolate', 'candy', 'lollipop',
        'a cup of coffee', 'a cup of tea', 'a glass of juice', 'a glass of milk', 'a glass of soda',
        'an egg', 'a fried egg', 'scrambled eggs', 'bacon', 'a piece of cheese', 'yogurt', 'cereal'
    ],
    places: [
        'a beach', 'a sandy beach', 'a tropical beach', 'a rocky beach', 'ocean waves on a beach',
        'a forest', 'a dense forest', 'a pine forest', 'a tropical jungle', 'a bamboo forest', 'woodland trees',
        'a city street', 'a busy city sidewalk', 'a quiet residential street', 'a downtown skyline', 'a tall skyscraper',
        'a mountain', 'a snowy mountain peak', 'a mountain range', 'a steep cliff', 'a rocky hillside',
        'a desert', 'a sandy desert with dunes', 'a desert with cactus', 'a dry canyon', 'an arid wasteland',
        'a kitchen', 'a modern kitchen', 'a cozy kitchen', 'a restaurant kitchen',
        'a bedroom', 'a cozy bedroom', 'a child\'s bedroom', 'a hotel room',
        'a bathroom', 'a living room', 'a dining room', 'a hallway', 'a basement', 'an attic',
        'an office', 'an open plan office', 'a home office', 'a meeting room', 'a cubicle',
        'a classroom', 'an empty classroom', 'a school hallway', 'a library', 'a college lecture hall',
        'a park', 'a city park', 'a playground', 'a sports field', 'a garden', 'a flower garden', 'a vegetable garden',
        'a grocery store aisle', 'a supermarket', 'a shopping mall', 'a clothing store', 'a bookstore',
        'a restaurant', 'a cafe', 'a coffee shop', 'a fast food restaurant', 'a bar',
        'a hospital room', 'a doctor\'s office', 'a dentist\'s office', 'an emergency room',
        'a museum', 'an art gallery', 'a theater', 'a movie theater', 'a concert hall', 'a stage',
        'an airport', 'a train station', 'a bus station', 'a subway platform', 'a parking lot', 'a parking garage',
        'a farm', 'a barn', 'a wheat field', 'a vineyard', 'an orchard', 'a meadow',
        'a river', 'a lake', 'a pond', 'a waterfall', 'a stream',
        'a cave', 'an underground tunnel', 'a road through the countryside', 'a highway', 'a bridge over water',
        'a castle', 'an old church', 'a temple', 'a mosque', 'a pyramid', 'a lighthouse',
        'outer space', 'the surface of the moon', 'a view from space',
        'underwater', 'a coral reef', 'the deep ocean'
    ]
};
