// Drives the dev-only block-thumbnail-harness page to produce a JPEG
// thumbnail for every tip with `_capturedBlocks`, then writes the result
// to src/lib/libraries/tips/block-thumbnails-cache.json.
//
// Invoked indirectly via `npm run generate-block-thumbnails`, which only
// fires this spec when the content hash of tips.json blocks has changed.
// See scripts/generate-tip-block-thumbnails.mjs.

const {test} = require('@playwright/test');
const fs = require('fs');
const path = require('path');

const TIPS_JSON_PATH = path.resolve(__dirname, '../../src/lib/libraries/tips/tips.json');
const CACHE_PATH = path.resolve(__dirname, '../../src/lib/libraries/tips/block-thumbnails-cache.json');
const RENDERER_VERSION = 'v1-96px-q92';

// Hash is computed by the wrapper script (scripts/generate-tip-block-thumbnails.mjs)
// and passed in via env var so both sides agree without sharing module systems.
const CONTENT_HASH = process.env.BLOCK_THUMBNAIL_CONTENT_HASH || '';

// Only run when explicitly invoked by the wrapper script — keeps the
// regular `npx playwright test` run from rewriting the cache file.
test.skip(
    !process.env.BLOCK_THUMBNAIL_CONTENT_HASH,
    'Run via `npm run generate-block-thumbnails`, not the regular test suite.'
);

test('generate block thumbnails for all tips with _capturedBlocks', async ({page}) => {
    test.setTimeout(10 * 60 * 1000); // up to 10 minutes for 70+ tips

    const tipsJson = JSON.parse(fs.readFileSync(TIPS_JSON_PATH, 'utf-8'));
    const tips = tipsJson.tips;

    const tipIds = Object.keys(tips).filter(
        id => Array.isArray(tips[id]._capturedBlocks) && tips[id]._capturedBlocks.length > 0
    );

    const failures = [];
    page.on('pageerror', err => failures.push(`pageerror: ${err.message}`));

    const baseURL = process.env.BLOCK_THUMBNAIL_BASE_URL || 'http://localhost:8601';
    await page.goto(`${baseURL}/block-thumbnail-harness.html`);
    await page.waitForFunction(() => window.__harnessReady === true, null, {timeout: 30000});
    await page.evaluate(() => document.fonts && document.fonts.ready);

    const thumbnails = {};

    for (let i = 0; i < tipIds.length; i++) {
        const tipId = tipIds[i];
        try {
            await page.evaluate(id => window.__renderTipBlocks(id), tipId);
            const dataUrl = await page.evaluate(() => window.__captureFirstTopBlock());
            thumbnails[tipId] = dataUrl;
            // eslint-disable-next-line no-console
            console.log(`[block-thumbnails] ${i + 1}/${tipIds.length} ${tipId}`);
        } catch (err) {
            // eslint-disable-next-line no-console
            console.warn(`[block-thumbnails] FAILED ${tipId}: ${err.message}`);
            failures.push(`${tipId}: ${err.message}`);
        }
    }

    const cache = {
        _comment: 'Auto-generated by scripts/generate-tip-block-thumbnails.mjs — do not edit by hand',
        rendererVersion: RENDERER_VERSION,
        contentHash: CONTENT_HASH,
        thumbnails
    };

    fs.writeFileSync(CACHE_PATH, `${JSON.stringify(cache, null, 2)}\n`);
    // eslint-disable-next-line no-console
    console.log(`[block-thumbnails] Wrote ${Object.keys(thumbnails).length} thumbnails to ${CACHE_PATH}`);

    if (failures.length > 0) {
        // eslint-disable-next-line no-console
        console.warn(
            `[block-thumbnails] ${failures.length} tip(s) failed to render — cache still written for the rest.`
        );
        for (const f of failures) {
            // eslint-disable-next-line no-console
            console.warn(`  - ${f}`);
        }
    }
});
