// Example projects shown in the Songs welcome modal.
//
// Each `sb3` import resolves (via webpack's asset/resource rule) to a URL that is
// fetched and handed to vm.loadProject() when the card is clicked. Thumbnails are
// screenshots of each project mid-play (see test/playwright/songs-examples.spec.js).
// The projects themselves are generated by starters/make-songs-examples.mjs.

import thumbDance from './starters/songs-example-1.png';
import thumbComposition from './starters/songs-example-2.png';
import thumbGame from './starters/songs-example-3.png';

import sb3Dance from './starters/songs-example-1.sb3';
import sb3Composition from './starters/songs-example-2.sb3';
import sb3Game from './starters/songs-example-3.sb3';

const starters = [
    {
        id: 'dance-party',
        title: 'Dance Party',
        description: 'A crew of dancers moves in time to the beats and notes of the song.',
        thumbnail: thumbDance,
        sb3: sb3Dance
    },
    {
        id: 'composition',
        title: 'Composition',
        description: 'Watch the band build up track by track, or click an instrument ' +
            'to cue it in and out yourself.',
        thumbnail: thumbComposition,
        sb3: sb3Composition
    },
    {
        id: 'game',
        title: 'Gem Hunt',
        description: 'Roam and collect the gems. Each one you grab adds a layer to the ' +
            'music — collect them all for a victory finish.',
        thumbnail: thumbGame,
        sb3: sb3Game
    }
];

export default starters;
